### ISSUE TITLE
Small main terminal

### ISSUE THREAD

**Issue by Niconoko** [wijes/TerminalDesktop#3] opened 2024-01-11 10:45 UTC
![image](https://github.com/wijes/TerminalDesktop/assets/24541618/c15d78f7-e2cc-4721-b071-33a2c653dd49)
This is the code: 018cf81f-ab58-fb45-c340-73cb6d406fc7

**Comment by UmbraMortem13** [comment] 2024-01-12 02:39
I have the same issue, I found out it is HDLethalCompany by Sligili. Unfortunately I can't compromise on that mod, so I do hope this is fixed soon. I can't introduce it to my group until this compatibility bug is fixed.

**Comment by wijes** [comment] 2024-01-12 11:20
Try the new version 0.5.5, the bug should be fixed

**Comment by Niconoko** [comment] 2024-01-12 12:09
Hm.. it fixed yeah, but now me can't type on it. (´・ω・｀)

**Comment by UmbraMortem13** [comment] 2024-01-12 12:12
Appears to be fixed with HDLethalCompany by Sligili, I could not reproduce the issue after a couple launches/config changes.

as for typing on it, you have to click on the terminal window. If you click on any other desktop window, resize the terminal, or move it, you must click back on the text to "focus" onto typing on it

**Closed as completed** 2024-01-13 08:11 UTC
